# Generated by Django 4.0.6 on 2022-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.IntegerField()),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=250)),
                ('service_required', models.CharField(max_length=250)),
            ],
        ),
    ]
